security:
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 12
    firewalls:
        main:
            form_login:
                login_path: app_auth
                check_path: app_login
                default_target_path: /home
            logout:
                path: app_logout
                target: /auth
            custom_authenticator: App\Security\AuthAuthenticator
            entry_point: App\Security\AuthAuthenticator
    access_control:
#        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }